### ISSUE TITLE
ABC Data format for multiple licenses in ABOUT file

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#331]
The current ABOUT files treat multiple licenses in string block
```
license_name: |
    Apache License 2.0
    Oasis WS Security Specification License
    W3C Software Notice and License
    WS-Policy Specification
license_file: |
    apache-2.0.LICENSE
    oasis-ws-security-spec.LICENSE
    w3c.LICENSE
    ws-policy-specification.LICENSE
license_url: |
    http://spgallery.arrs.arrisi.com/urn/?urn=urn:dje:license:apache-2.0
    http://spgallery.arrs.arrisi.com/urn/?urn=urn:dje:license:oasis-ws-security-spec
    http://spgallery.arrs.arrisi.com/urn/?urn=urn:dje:license:w3c
    http://spgallery.arrs.arrisi.com/urn/?urn=urn:dje:license:ws-policy-specification
etc...
```
However, in the ABC Data format, we should use a list instead.
For instance,
```
licenses:
     - key: apache-2.0
       name: Apache License 2.0
       file: apache-2.0.LICENSE
       url: http://spgallery.arrs.arrisi.com/urn/?urn=urn:dje:license:apache-2.0

     - key: oasis-ws-security-spec
       name: Oasis WS Security Specification License
       file: oasis-ws-security-spec.LICENSE
       url: http://spgallery.arrs.arrisi.com/urn/?urn=urn:dje:license:oasis-ws-security-spec
....
```

**Comment by tdruez** [comment]
The multi-license support is now needed on the DejaCode side to generate proper AboutFiles from a Component/Package. See https://github.com/nexB/dejacode/issues/728

@chinyeungli @pombredanne could we raise the priority of this one in the current `aboutcode-toolkit` milesone?

**Comment by chinyeungli** [comment]
yes. I will work on this.

**Comment by tdruez** [comment]
Here's the current output in DejaCode:

```
name: uritemplate
version: 3.0.0
license_expression: apache-2.0 OR bsd-new
licenses:
-   file: apache-2.0.LICENSE
    key: apache-2.0
    name: Apache License 2.0
-   file: bsd-new.LICENSE
    key: bsd-new
    name: BSD-3-Clause

[...]
```

We need to raise the priority on this one since the ABOUT files generated by `DejaCode` cannot be validated by `aboutcode-toolkit`.

**Comment by chinyeungli** [comment]
Thanks. This will be my focus once I have a break from the audit work

**Comment by chinyeungli** [comment]
The https://github.com/nexB/aboutcode-toolkit/tree/331_multi_lic_support_refresh should have this fixed.
Current output of a "sample" ABOUT file
```
about_resource: test.c
about_resource_path: test.c
license_expression: mit AND bsd-new
licenses:
    -   file: mit.LICENSE
        key: mit
        name: MIT License
        url: https://enterprise.dejacode.com/urn/?urn=urn:dje:license:mit
    -   file: bsd-new.LICENSE
        key: bsd-new
        name: BSD-3-Clause
        url: https://enterprise.dejacode.com/urn/?urn=urn:dje:license:bsd-new
name: AboutCode-toolkit
```
