### ISSUE TITLE
Introduce component field for component

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#340]
Here is how we will treat components:
```
about_resource: boolean.py-3.6-py2.py3-none-any.whl

md5: da39999eb131b589e84ad935dc4ca642
sha1: d31b55e7ad2ee917232b3213afe3ae9678156a9f

download_url: https://files.pythonhosted.org/boolean.py-3.6-py2.py3-none-any.whl

component:
    name: boolean.py
    version: '3.6'
    description: Implements boolean algebra in one module.
    owner: Sebastian Kraemer
    license_expression: bsd-new

copyright: Copyright (c) 2009-2016 Sebastian Kraemer, basti.kr@gmail.com and others

homepage_url: https://github.com/bastikr/boolean.py

license_expression: bsd-simplified
license_file: bsd-simplified.LICENSE

notice_file: boolean.py-3.6-py2.py3-none-any.whl.NOTICE
notice_url: https://github.com/bastikr/boolean.py/blob/master/LICENSE.txt

attribute: true
```
