### ISSUE TITLE
New YAML output review

### ISSUE THREAD

**Issue by tdruez** [aboutcode-org/aboutcode-toolkit#349]
Comparing current output from DejaCode:
```
about_resource: django_rest_hooks-1.5.0-py2.py3-none-any.whl
attribute: true
checksum_md5: 7e37315a6572c6771ba6877392fb18ed
checksum_sha1: 4007c278d712146a6e07acea505afe1ef4ea5941
copyright: Copyright (c) 2016 Zapier Inc.
description: Add webhook subscriptions to your Django app.
download_url: https://pypi.python.org/packages/95/b3/53614fb7dc59fe86f54cdb5366d35f2efea20c54c66a828aa69e8070cc70/django_rest_hooks-1.5.0-py2.py3-none-any.whl#md5=7e37315a6572c6771ba6877392fb18ed
homepage_url: https://github.com/zapier/django-rest-hooks
license_expression: isc
licenses:
-   file: isc.LICENSE
    key: isc
    name: ISC License
name: django-rest-hooks
notice_file: django_rest_hooks-1.5.0-py2.py3-none-any.whl.NOTICE
notice_url: https://github.com/zapier/django-rest-hooks/blob/master/LICENSE.md
owner: Zapier
version: 1.5.0
```

To the output generated by aboutcode-toolkit `About().dumps()` version 3.2.2:
```
about_resource: django_rest_hooks-1.5.0-py2.py3-none-any.whl
attribute: yes
checksum_md5: 7e37315a6572c6771ba6877392fb18ed
checksum_sha1: 4007c278d712146a6e07acea505afe1ef4ea5941
copyright: Copyright (c) 2016 Zapier Inc.
description: >-
    Add webhook subscriptions to your Django app.
download_url:
    - https://pypi.python.org/packages/95/b3/53614fb7dc59fe86f54cdb5366d35f2efea20c54c66a828aa69e8070cc70/django_rest_hooks-1.5.0-py2.py3-none-any.whl#md5=7e37315a6572c6771ba6877392fb18ed
homepage_url:
    - https://github.com/zapier/django-rest-hooks
license_expression: isc
licenses:
    -   file: isc.LICENSE
        key: isc
        name: ISC License
name: django-rest-hooks
notice_file: django_rest_hooks-1.5.0-py2.py3-none-any.whl.NOTICE
notice_url:
    - https://github.com/zapier/django-rest-hooks/blob/master/LICENSE.md
owner:
    - Zapier
redistribute: yes
track_changes: yes
version: 1.5.0
```

Why are the following field displayed as list: download_url, homepage_url, notice_url, owner?
Also, why the indent for license is `    -   ` while it's `    - ` for other list type field?
Lastly, the field ordering looks alphabetical, is this wanted?
