### ISSUE TITLE
Attrib command doesn't detect common licenses not in lower case

### ISSUE THREAD

**Issue by grv87** [aboutcode-org/aboutcode-toolkit#405]
Given that `license_expression` contains license keys not in lower case, for example:
```
...
license_expression: Apache-2.0
licenses:
  - key: Apache-2.0
    name: Apache License 2.0
    file: LICENSE
```
the license is not detected as common by `attrib` command.

The problem is here:
https://github.com/nexB/aboutcode-toolkit/blob/3264859560ea843041483bdc4807eac9b1e2607c/templates/default_html.template#L47
`common_licenses` contains only lower-cased ids, so capitalized id is not detected.
