### ISSUE TITLE
Order of license files/ids is lost

### ISSUE THREAD

**Issue by grv87** [aboutcode-org/aboutcode-toolkit#406]
I would like to run `attrib` with custom template, so it would print all licenses along with their ids.
Something like that:
```
{% for i in range(about_object.license_file.value|length) %}
  <h2>{{ about_object.license_key.value[i] | e}}</h2>
  <pre>{{ about_object.license_file.value.values()[i] | e}}</pre>
{% endfor %}
```

The problem is that `license_key` field doesn't keep its order from ABOUT file.
Given ABOUT file:
```
...
license_expression: LGPL-3.0-or-later OR Apache-2.0
licenses:
  - key: Apache-2.0
    name: Apache License 2.0
    file: LICENSES/Apache-2.0.txt
  - key: LGPL-3.0-or-later
    name: LGPL
    file: LICENSES/LGPL-3.0.txt
```
I got the incorrect results, Apache text named LGPL and vice versa.

The problem seems to be here:
https://github.com/nexB/aboutcode-toolkit/blob/57dc7455874f2d878cdbc7bd6369c676e2ee8e7f/src/attributecode/model.py#L1091

License keys are just overridden, and files are not processed at all.

**Comment by grv87** [comment]
No, the problem is not there. My mistake.
Looks like it is just not possible with the current model at all :(

**Comment by chinyeungli** [comment]
thanks for the report. I will look into this

**Comment by chinyeungli** [comment]
@grv87 I am looking at this now
```
license_expression: LGPL-3.0-or-later OR Apache-2.0
licenses:
  - key: Apache-2.0
    name: Apache License 2.0
    file: LICENSES/Apache-2.0.txt
  - key: LGPL-3.0-or-later
    name: LGPL
    file: LICENSES/LGPL-3.0.txt
```
I believe what you are saying is the order of how the license text display in the attribution should follow the order of the `license_expression`. 
Meaing if `license_expression: LGPL-3.0-or-later OR Apache-2.0`, the LGPL should be displayed first and then the Apache 2.0 while `license_expression: Apache-2.0 OR LGPL-3.0-or-later` should display Apache 2.0 followed by the LGPL? (Putting the #405 common license issue aside)


I've tried to reproduce the issue.
Here is the result:
```
This component is licensed under LGPL-3.0-or-later OR Apache-2.0

Apache License
                           Version 2.0, January 2004
                        http://www.apache.org/licenses/

   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
.........
   See the License for the specific language governing permissions and
   limitations under the License.
                   GNU LESSER GENERAL PUBLIC LICENSE
                       Version 3, 29 June 2007

 Copyright (C) 2007 Free Software Foundation, Inc. <https://fsf.org/>
 Everyone is permitted to copy and distribute verbatim copies
 of this license document, but changing it is not allowed.
.........
```
(perhaps there should be a divider to separate the two licenses.)

However, I am not sure what do you mean by
> I got the incorrect results, Apache text named LGPL and vice versa.
> License keys are just overridden, and files are not processed at all.

Can you elaborate a bit?
