### ISSUE TITLE
How to consolidate custom licenses?

### ISSUE THREAD

**Issue by DorsalGreen** [aboutcode-org/aboutcode-toolkit#438]
Hello,
I want to generate an attribution notice, where each license is only printed once in full. Currently, it is always printed in full for each file that uses that license. It works only, if I add my custom license name to the license.py file.  As you can see, I used the exact same name, key, and file name
What is the correct way to consolidate custom licenses (i.e. any licenses that are not in license.py)?
For example, I have my licenses with a license key according to SPDX, but consolidating license texts seems only to work with dejacode license keys.

Steps to reproduce:
first.ABOUT
[first.ABOUT.txt](https://github.com/nexB/aboutcode-toolkit/files/5079374/first.ABOUT.txt)

```
about_resource: first
name: first
attribute: yes
licenses:
    -   file: myCustom-1.0.LICENSE
        key: myCustom-1.0
        name: My Custom Common Licenses (MCCL)
```

second.ABOUT
[second.ABOUT.txt](https://github.com/nexB/aboutcode-toolkit/files/5079375/second.ABOUT.txt)

```
about_resource: second
name: second
attribute: yes
licenses:
    -   file: myCustom-1.0.LICENSE
        key: myCustom-1.0
        name: My Custom Common Licenses (MCCL)
```
myCustom-1.0.LICENSE
[myCustom-1.0.LICENSE.txt](https://github.com/nexB/aboutcode-toolkit/files/5079382/myCustom-1.0.LICENSE.txt)

`My common license text.`

Run: `about attrib example2 example2\out.html`

What I get: (The license is repeated in full for each entry.)
[out_not_consolidated.html.txt](https://github.com/nexB/aboutcode-toolkit/files/5079377/out_not_consolidated.html.txt)

```
OPEN SOURCE SOFTWARE INFORMATION
Licenses, acknowledgments and required copyright notices for open source components:

first

second

first
My common license text.
second
My common license text.
Common Licenses Used in This Product
End
```

What I want: (The license is only printed in full at the end.)
[out_consolidated.html.txt](https://github.com/nexB/aboutcode-toolkit/files/5079378/out_consolidated.html.txt)

```
OPEN SOURCE SOFTWARE INFORMATION
Licenses, acknowledgments and required copyright notices for open source components:

first

second

first
Full text of myCustom-1.0 is available at the end of this document.

second
Full text of myCustom-1.0 is available at the end of this document.

Common Licenses Used in This Product
myCustom-1.0
My common license text.
End
```
