### ISSUE TITLE
Please strip carriage return from multiline-license texts

### ISSUE THREAD

**Issue by OctagonHex** [aboutcode-org/aboutcode-toolkit#443]
Under Windows, I create a .csv file with the following contents:
```
# Generated with AboutCode Toolkit Version 5.0.0 

about_resource,name,version,license_key,license_file
3rdParty/test,test,1.5,"License1
License2
License3","LIC1.LICENSE
LIC2.LICENSE
LIC3.LICENSE"
```
where all line ending are: \r\n

Now, the generated .ABOUT file reads like this
```
# Generated with AboutCode Toolkit Version 5.0.0 

about_resource: test
name: test
version: '1.5'
licenses:
  - key: License1
    file: "LIC1.LICENSE\r"
  - key: License2
    file: "LIC2.LICENSE\r"
  - key: License3
    file: LIC3.LICENSE
```
The text \r is litterly written there, as the escapced string.

Could you please strip this special character the input for that text element before writing it, so it will work more robust on Windows.
