### ISSUE TITLE
license issues for `gen` and `attrib`

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#450]
This line will fail https://github.com/nexB/aboutcode-toolkit/blob/develop/src/attributecode/attrib.py#L112 with the following scenario:
**Input**
`license_expression: apache-2.0 AND custom` and with no `license_name` provided
The `license_name_list` and `lic_list` is supposed to be a 1 to 1 matching relationship
However, if no `license_name` is provided in the input and only the above `license_expression` is provided
Since the `custom` is not a valid scancode license key, the `fetch-license` in `gen` will produce something like this following:
```
licenses:
  - key: apache-2.0
    name: Apache License 2.0
    file: apache-2.0.LICENSE
  - key: custom
```
As a result, it'll have 2 license_keys with 1 license_name which make the code fail. (Although the tool will prompt error to notify `custom` is not a valid scancode license key in the `gen` process)
